name: build docs

# Pillow > 9.5.0 no longer includes 32-bit wheels.

# runners
#   https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#   windows-2019
#   windows-2022
#   or windows-latest

on:
  workflow_call

jobs:
  jobs_1: # make docs
    
    strategy:
      matrix:
        python_version: [ "3.10", ] # python version
        os: [ windows-latest , ]
    
    runs-on: ${{ matrix.os }} 
    
    defaults:
      run:
        shell: cmd
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
        
    - name: Install sphinx
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --prefer-binary --upgrade sphinx sphinx-rtd-theme
        python -m pip install --upgrade jieba
    
    - name: build docs
      run: |
        python -m sphinx -b html -d docs_build\.doctrees docs\source docs_build\html
    - name: 7z
      run: |
        7z a -t7z "docs.7z" .\docs_build\html\*
        dir
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: "docs"
        path: "docs.7z"
