name: exe x86 x64

# Pillow > 9.5.0 no longer includes 32-bit wheels.

# runners
#   https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#   windows-2019
#   windows-2022
#   or windows-latest

on:
  workflow_call

jobs:
  jobs_1: # build exe 
    
    env:
      file_name_start:   ${{    startsWith( github.ref_name, 'v' )  && format( 'JJui_{0}',github.ref_name ) || 'JJui' }}
    
    strategy:
      matrix:
        architecture: [ x86 ,x64 ] # python x86 ,x64
        python_version: [ "3.11" ,] # python version
        os: [ windows-2019, ] # windows-2022 
    
    runs-on: ${{ matrix.os }} 
    
    defaults:
      run:
        shell: cmd
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
        architecture: ${{ matrix.architecture }}
        
    - name: Install pillow pyinstaller
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --only-binary :all: --upgrade pillow
        python -m pip install --prefer-binary --upgrade pyinstaller
    
    - name: pyinstaller to exe
      run: |
        python .windows_build_exe_use_pyinstaller.py
    - name: 7z
      run: |
        7z a -t7z -mx=9 "${{ env.file_name_start }}_${{ matrix.os }}_python_${{ matrix.python_version }}_${{ matrix.architecture }}.7z" .\dist\*
        dir
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: "${{ env.file_name_start }}_${{ matrix.os }}_python_${{ matrix.python_version }}_${{ matrix.architecture }}"
        path: "${{ env.file_name_start }}_${{ matrix.os }}_python_${{ matrix.python_version }}_${{ matrix.architecture }}.7z"
