name: macos-12 pyinstaller test

on: workflow_dispatch


jobs:
  jobs_1: 
    runs-on: macos-12
    
    defaults:
      run:
        shell: bash
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install --upgrade wheel
        python -m pip install pillow
        python -m pip install pyinstaller
    
    - name: pyinstaller to executable
      run: source .mac_pyinstaller.sh
      
    - name: tar 7z
      run: |
        tar -cf JJui.tar dist
        7z a -t7z "JJui.7z" JJui.tar
        ls -l
        
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: JJui
        path: JJui.7z
