name: manually prerelease latest

on: workflow_dispatch

# {owner}/{repo}/.github/workflows/{filename}@{ref} for reusable workflows in public and private repositories.
# ./.github/workflows/{filename} for reusable workflows in the same repository

jobs:
  jobs_1:
    uses: ./.github/workflows/exe.yml
  jobs_2:
    uses: ./.github/workflows/exe_x86.yml
  jobs_3:
    uses: ./.github/workflows/docs.yml
    
  jobs_last:
    if: ${{ always() }}
    needs: [jobs_1,jobs_2,jobs_3]
    
    runs-on: windows-latest
    
    permissions:
      contents: write

    defaults:
      run:
        shell: cmd
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: prerelease
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: latest
        files: |
          artifacts/**/*.7z

