name: Windows Release Test

# Pillow > 9.5.0 no longer includes 32-bit wheels.

# runners
#   https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#   windows-2019
#   windows-2022
#   or windows-latest

on:
  push:
    tags:
      - "*"

jobs:
  jobs_1: # build exe 
    uses: ./.github/workflows/exe.yml
  jobs_2:
    uses: ./.github/workflows/exe_x86.yml
  jobs_3:
    uses: ./.github/workflows/docs.yml
  jobs_last: # release
    if: ${{ always() }}
    needs: [jobs_1,jobs_2,jobs_3]
    
    runs-on: windows-latest
    
    permissions:
      contents: write
    
    defaults:
      run:
        shell: cmd
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: download
      uses: actions/download-artifact@v3
      with:
        path: artifacts 
        # name 未指定名称，每一个文件，会包含在一个文件夹里
    - name: list file
      run: |
        dir
        echo ......
        dir artifacts
        echo ......
        tree artifacts /F
    - name: release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/**/*.7z"
        token: ${{ secrets.GITHUB_TOKEN }}
