name: test5

on: workflow_dispatch


jobs:
  jobs_1: # build exe 
    
    strategy:
      matrix:
        architecture: [ x64 , ] # python x86 ,x64
        python_version: [ "3.11","3.12" ] # python version
        os: [ windows-2019, windows-2022 ]
    
    runs-on: ${{ matrix.os }} 
    
    defaults:
      run:
        shell: cmd
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
        architecture: ${{ matrix.architecture }}
        
    - name: Install pillow pyinstaller
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --only-binary :all: --upgrade pillow
        python -m pip install --prefer-binary --upgrade pyinstaller
    
    - name: pyinstaller to exe
      run: |
        python .windows_build_exe_use_pyinstaller.py
    - name: 7z
      run: |
        7z a -t7z -mx=9 "JJui_${{ github.ref_name }}_${{ matrix.os }}_python_${{ matrix.python_version }}_${{ matrix.architecture }}.7z" .\dist\*
        dir
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: "JJui_${{ github.ref_name }}_${{ matrix.os }}_python_${{ matrix.python_version }}_${{ matrix.architecture }}"
        path: "JJui_${{ github.ref_name }}_${{ matrix.os }}_python_${{ matrix.python_version }}_${{ matrix.architecture }}.7z"
      
        



