name: test

# Pillow > 9.5.0 no longer includes 32-bit wheels.

# runners
#   https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#   windows-2019
#   windows-2022
#   or windows-latest

on:
  workflow_call

jobs:
  jobs_1: # build exe 

    env:
      file_name_start:   ${{    startsWith( github.ref_name, 'v' )  && format( 'JJui_{0}',github.ref_name ) || 'JJui' }}
      file_name_start_2: ${{ (!startsWith( github.ref_name, 'v' ))  && format( 'JJui_{0}',github.ref_name ) || 'JJui' }}
      # ${{ startsWith( github.ref_name, 'v' ) && github.ref_name || 'other' }}

    strategy:
      matrix:
        architecture: [ x64 , ] # python x86 ,x64
        python_version: [ "3.10", ] # python version
        os: [ windows-2019, ]
    
    runs-on: ${{ matrix.os }} 
    
    defaults:
      run:
        shell: cmd
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
        architecture: ${{ matrix.architecture }}
        
    - name: test
      run: |
        echo env.file_name_start
        echo ${{ env.file_name_start }}
        echo %file_name_start%
        echo %file_name_start_2%
