name: test3

on: workflow_dispatch

jobs:
  jobs_1: 
    runs-on: macos-10.15
    
    defaults:
      run:
        shell: bash
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: pyinstaller to executable
      run: |
        python3 --version
        python3 -m pip list
      
      

