name: test

on: workflow_dispatch


jobs:
  jobs_1: 
    runs-on: macos-latest 
    
    defaults:
      run:
        shell: bash
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: show python version
      run: |
        python -V -V
    
    - name: Variables
      run: |
        echo ......
        echo ......
        echo runner.name
        echo ${{ runner.name }}
        
        echo RUNNER OS
        echo $RUNNER_OS
        echo ${{ runner.os }}
        
        echo RUNNER ARCH
        echo $RUNNER_ARCH
        echo ${{ runner.arch }}
        
        echo ......
        echo ......
        echo github event_name
        echo ${{ github.event_name }}
        
        echo push ref
        echo github event ref
        echo ${{ github.event.ref }}
        
        echo GITHUB_REF_NAME
        echo $GITHUB_REF_NAME%
        echo ${{ github.ref_name }}
        
    - name: path
      run: |
        echo ......
        echo pwd
        pwd
        echo ......
        echo ls -l
        ls -l
        echo ......
        echo whereis 7z
        whereis 7z
        echo ......
        echo PATH
        echo $PATH

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install --upgrade wheel
        python -m pip install pillow
        python -m pip install pyinstaller
    
    - name: pyinstaller to exe
      run: |
        python -m PyInstaller --add-data .jjui:.jjui --add-data jjui_source/images:jjui_source/images --add-data jjui_source/ui_translation:jjui_source/ui_translation --icon jjui_source/images/for-icon.png JJui.pyw
        python -m PyInstaller --add-data .jjui:.jjui --add-data jjui_source/images:jjui_source/images --add-data jjui_source/ui_translation:jjui_source/ui_translation --icon jjui_source/images/for-icon.png JJui_sl.pyw
    - name: 7z
      run: |
        7z a -t7z "JJui_test.7z" ./dist/*
        ls -l
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: JJui_test
        path: JJui_test.7z
      
